# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from suggestpb import suggest_pb2 as suggestpb_dot_suggest__pb2


class SuggestStub(object):
    """Hotpepperグルメで取得したお店を元にプランを提案する
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Suggest = channel.unary_unary(
                '/suggest.Suggest/Suggest',
                request_serializer=suggestpb_dot_suggest__pb2.SuggestRequest.SerializeToString,
                response_deserializer=suggestpb_dot_suggest__pb2.SuggestResponse.FromString,
                )


class SuggestServicer(object):
    """Hotpepperグルメで取得したお店を元にプランを提案する
    """

    def Suggest(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SuggestServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Suggest': grpc.unary_unary_rpc_method_handler(
                    servicer.Suggest,
                    request_deserializer=suggestpb_dot_suggest__pb2.SuggestRequest.FromString,
                    response_serializer=suggestpb_dot_suggest__pb2.SuggestResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'suggest.Suggest', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Suggest(object):
    """Hotpepperグルメで取得したお店を元にプランを提案する
    """

    @staticmethod
    def Suggest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/suggest.Suggest/Suggest',
            suggestpb_dot_suggest__pb2.SuggestRequest.SerializeToString,
            suggestpb_dot_suggest__pb2.SuggestResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
